"""Average-of-configuration open-shell atoms.

Every ion this project actually targets — Ti(III) d1, Ce(III) 4f1, Dy(III) 4f9, Yb(III)
4f13, Bi 6p3 — is open shell, so none of them can be treated without this. The risk on this path is not that average-of-configuration fails loudly but that it
fails *quietly*: an aufbau occupation of a degenerate manifold converges cleanly, looks
entirely reasonable, and carries an arbitrary spatial orientation into the mean field.

The tests are ordered by what they can catch.

1. **The occupation rule itself**, with no SCF at all. It is pure arithmetic
   (:func:`kuiva.amf.configuration.average_occupations`) and asserting the *value* of the
   fraction is what distinguishes averaging over a whole ``l`` shell from averaging within a
   ``j`` sub-shell — both are spherical, and only one is average-of-configuration.

2. **The configuration is canonical and hashable**, as the cache key requires: the sensitivity
   study below *depends* on a neutral and an ionic reference not aliasing in the cache, and
   equally on two spellings of one reference not being solved twice.

3. **The converged density is spherical**, which under AOC is the assertion that the averaging
   worked rather than a closed-shell restriction. The complementary
   negative — that an aufbau occupation is caught — is in ``test_amf_backend.py``.

4. **The X2CAMF energy functional against four-component DHF, same basis, same configuration.**
   This is the validation workhorse, generalized to open shells *first*, because it is cheap,
   needs no external program, and is what tells you whether an AOC correction is right long
   before any cross-code reference does. ⚠ The
   two-component side must occupy **the same configuration the same way**, or the comparison
   is between two different states; that is why both sides go through
   :func:`kuiva.amf.configuration.average_occupations` rather than through two implementations
   of one rule.

5. **The reference configuration is a real choice**, and how much it matters is measured
   rather than asserted.

Cost
----
The occupation and configuration tests are instant. Carbon and oxygen four-component solves
are sub-second. Ti(3+) is ~25 s and is marked ``slow``; the lanthanides are minutes to tens of
minutes uncontracted and are **not** in the suite at all — they are
generated by ``tests/generate/amf_open_shell_cost.py`` and
``tests/generate/amf_sensitivity.py`` under an explicit budget, under an explicit budget.
"""
import numpy as np
import pytest
from pyscf import gto

from kuiva.amf import amf_correction, validate_correction
from kuiva.amf.atomic import atomic_solution, cache_statistics, clear_cache, make_request
from kuiva.amf.configuration import (AtomicConfiguration, OpenShell,
                                    average_occupations,
                                    install_configuration_average)
from kuiva.amf.pyscf_dhf import SPHERICAL_DENSITY_TOLERANCE, _density_anisotropy

BASIS = "x2c-SVPall-2c"
HARTREE_CM = 219474.6313632


def atom(symbol, basis=BASIS, charge=0):
    return gto.M(atom=[(symbol, (0.0, 0.0, 0.0))], basis=basis, charge=charge,
                 spin=(int(gto.charge(symbol)) - charge) % 2, verbose=0)


# --- 1. The occupation rule, with no SCF ---------------------------------------------------

@pytest.mark.parametrize("configuration,l,fraction,degeneracy", [
    ("[Ar]3d1", 2, 1.0 / 10.0, 10),        # Ti(3+): one d electron over ten d spinors
    ("[Xe]4f1", 3, 1.0 / 14.0, 14),        # Ce(3+)
    ("[Xe]4f9", 3, 9.0 / 14.0, 14),        # Dy(3+)
    ("[Xe]4f13", 3, 13.0 / 14.0, 14),      # Yb(3+)
    ("[Xe]4f14 5d10 6s2 6p3", 1, 0.5, 6),  # Bi 6p3
    ("[He]2s2 2p4", 1, 4.0 / 6.0, 6),      # O
])
def test_the_open_shell_fraction_is_over_the_whole_l_shell(configuration, l, fraction,
                                                           degeneracy):
    """``q / (4l+2)`` over **all** spinors of the frontier shell.

    ⚠ Asserting the *value* is the point. Bismuth's 6p3 is 0.5 on each of six spinors, not
    occupation 1 on ``6p_1/2`` and 0.25 on ``6p_3/2`` — and both of those give a spherical
    density, so the anisotropy guard cannot tell them apart. Only this can. Averaging within a
    ``j`` sub-shell would be a different (and non-standard) reference state whose spin-orbit
    splitting is biased toward the sub-shell it favours.
    """
    config = AtomicConfiguration.parse(configuration)
    # A generous orbital set of every l, ordered so that energy order is index order.
    angular = np.repeat(np.arange(5), 40)
    energies = np.arange(angular.size, dtype=float)
    occ = average_occupations(config, energies, angular)

    assert occ.sum() == pytest.approx(config.n_electrons, abs=1e-12)
    fractional = occ[(occ > 1e-12) & (occ < 1.0 - 1e-12)]
    assert fractional.size == degeneracy
    assert np.allclose(fractional, fraction)
    # ...and they are the *frontier* orbitals of that l, not an arbitrary subset of them.
    occupied_l = angular[occ > 1e-12]
    assert set(np.unique(occupied_l)) <= set(np.nonzero(config.occupations)[0])
    assert np.count_nonzero(occ[angular == l] > 1e-12) == config.spinors_needed(l)


def test_a_closed_shell_configuration_gives_integer_occupations():
    """The same rule with nothing left over. This is what licenses using one code path for
    both cases — and it is why every previously committed closed-shell number was
    reproduced unchanged when average-of-configuration replaced the energy-ordered fill."""
    config = AtomicConfiguration.parse("1s2 2s2 2p6")
    angular = np.repeat(np.arange(3), 20)
    occ = average_occupations(config, np.arange(angular.size, dtype=float), angular)
    assert set(np.unique(occ)) == {0.0, 1.0}
    assert occ.sum() == 10


def test_a_partially_filled_shell_needs_all_of_it_present():
    """The electrons are spread over the whole frontier shell, so a basis that can hold only
    the occupied part of it gives a wrong answer rather than a small one. Six ``f`` orbitals
    are enough for nine ``f`` electrons *by count* and are refused anyway."""
    config = AtomicConfiguration.parse("[Xe]4f9")
    angular = np.concatenate([np.repeat(np.arange(3), 40), np.full(6, 3)])
    with pytest.raises(RuntimeError, match="needs all 14 orbitals"):
        average_occupations(config, np.arange(angular.size, dtype=float), angular)


def test_energy_order_within_a_channel_is_what_decides():
    """Channels are filled independently and in *energy* order within each, which is what
    makes a cold start reproducible when 4f, 5d and 6s cross during the SCF (the lanthanide
    risk the open-shell path carries). Shuffling the orbitals must not change which of them end up
    occupied."""
    config = AtomicConfiguration.parse("[Ar]3d1")
    angular = np.repeat(np.arange(3), 30)
    energies = np.arange(angular.size, dtype=float)
    order = np.random.default_rng(0).permutation(angular.size)
    a = average_occupations(config, energies, angular)
    b = average_occupations(config, energies[order], angular[order])
    assert np.allclose(a[order], b)


# --- 2. The configuration as a cache key ---------------------------------------------------

def test_neutral_and_ionic_references_do_not_alias():
    """⚠ A cache-key requirement, and the thing the sensitivity study below depends on.

    A free-form provenance string once reached the cache key untouched, so a
    neutral and an ionic reference for the same element would have collided unless they
    happened to stringify differently — and the study measuring the difference between them
    would then have compared a result with itself.

    ⚠ Ce's *default* is now the trivalent ion, so the neutral reference has to be named
    explicitly here — which is exactly the comparison the sensitivity study makes.
    """
    neutral = make_request("Ce", "b", configuration="[Xe]4f1 5d1 6s2")
    ionic = make_request("Ce", "b", configuration="[Xe]4f1")
    assert neutral != ionic
    assert neutral.configuration.n_electrons == 58
    assert ionic.configuration.n_electrons == 55
    assert ionic.charge == 3                                # derived, not passed in
    assert make_request("Ce", "b").configuration == ionic.configuration   # the default


def test_the_default_reference_is_the_neutral_atom_outside_the_f_block():
    """The reference configuration. The atomic mean field is a property of an *element*, and a
    molecular charge belongs to no single atom of it — so the default cannot be inferred from
    ``mol.charge``, and a d-block ion's configuration is not derivable from a per-``l``
    electron count anyway (Ti(3+) is [Ar]3d1, not [Ar]4s1)."""
    assert make_request("Ti", "b").configuration == AtomicConfiguration.ground("Ti")
    assert make_request("Ti", "b", charge=3).configuration == AtomicConfiguration.ground("Ti")
    with pytest.raises(TypeError):
        AtomicConfiguration.ground("Ti", 3)                 # no such thing, deliberately


@pytest.mark.parametrize("element,expected", [
    ("La", "[Xe]"), ("Ce", "[Xe]4f1"), ("Gd", "[Xe]4f7"), ("Dy", "[Xe]4f9"),
    ("Yb", "[Xe]4f13"), ("Lu", "[Xe]4f14"),
    ("Ac", "[Rn]"), ("Th", "[Rn]5f1"), ("U", "[Rn]5f3"), ("Cm", "[Rn]5f7"),
])
def test_the_f_block_defaults_to_the_trivalent_ion(element, expected):
    """⚠ **A user decision on chemistry, not numerics**.

    Lanthanides are almost always encountered as Ln(3+). The neutral atom is wrong for them
    twice over: it is a state molecular chemistry essentially never sees, and **low-valent
    lanthanides do not retain their atomic configuration anyway** — the known Dy(II) complexes
    are 4f9(6s/5d)1, so neutral Dy's 4f10 describes nothing that occurs in a molecule while
    Dy(3+) 4f9 is what nearly every target system is.

    It is safe to *derive* only because an f-block trivalent ion is a closed noble-gas core
    plus an ``f`` shell, with nothing to decide. The same function refuses a d-block ion.
    """
    from kuiva.amf.configuration import default_configuration

    got = default_configuration(element)
    assert got == AtomicConfiguration.parse(expected)
    assert got.n_electrons == int(gto.charge(element)) - 3
    assert len(got.open_shells()) <= 1
    assert make_request(element, "b").configuration == got
    assert make_request(element, "b").charge == 3


@pytest.mark.parametrize("element,oxidation,expected", [
    # ⚠ The cases that motivated the feature: +3 is *not* universal across the f block.
    ("Th", 4, "[Rn]"),                    # thorium is usually tetravalent
    ("U", 6, "[Rn]"),                     # uranium and plutonium are high-valent
    ("Pu", 4, "[Rn]5f4"),
    ("No", 2, "[Rn]5f14"),                # late actinides are more stable divalent
    ("Eu", 2, "[Xe]4f7"),
    ("Ce", 4, "[Xe]"),
    ("Yb", 2, "[Xe]4f14"),
    # ...and off the f block, where a different rule applies.
    ("Ti", 3, "[Ar]3d1"),                 # not [Ar]4s1
    ("Fe", 2, "[Ar]3d6"), ("Fe", 3, "[Ar]3d5"), ("Cu", 2, "[Ar]3d9"),
    ("Bi", 3, "[Xe]4f14 5d10 6s2"),       # the inert pair
    ("Pb", 2, "[Xe]4f14 5d10 6s2"),
])
def test_an_oxidation_state_can_be_chosen_per_element(element, oxidation, expected):
    """⚠ **+3 is a default, not a claim, and the f block is where that matters** (user
    decision).

    There is no single standard oxidation state across the actinides: thorium is usually
    tetravalent, uranium and plutonium high-valent, and the late actinides such as nobelium
    more stable divalent. So the default has to be overridable per element, and it is.

    Two rules, and which one applies is decided by the block:

    * **f block** — ``[core] nf^(Z - Z_core - q)`` exactly, since the ion is a closed
      noble-gas core plus an ``f`` shell whatever ``q`` is.
    * **everything else** — remove from the occupied shell of highest ``n``, ties by highest
      ``l``. That gives Ti(III) [Ar]3d1 rather than [Ar]4s1, and the inert pair for Bi(III)
      and Pb(II). ⚠ It is **not** applied to the f block, where it would strip 5p before 4f and
      return [Xe]4f14 5s2 5p5 for Yb(3+) instead of [Xe]4f13 — ordering by ``n`` stops being
      ordering by orbital energy once 4f drops below 5p.
    """
    from kuiva.amf.configuration import AtomicConfiguration as Config

    got = Config.for_oxidation_state(element, oxidation)
    assert got == Config.parse(expected)
    assert got.n_electrons == int(gto.charge(element)) - oxidation


@pytest.mark.parametrize("spelling", ["+2", "2+", 2])
def test_an_oxidation_state_is_accepted_wherever_a_configuration_is(spelling):
    """``configuration="+2"`` needs no new parameter anywhere — it flows through the cache key
    and the provenance record like any other configuration, which is what keeps a per-element
    oxidation state from becoming a second way of saying the same thing."""
    got = AtomicConfiguration.coerce(spelling, "Yb")
    assert got == AtomicConfiguration.parse("[Xe]4f14")
    assert make_request("Yb", "b", configuration=spelling).charge == 2
    # ...and it is a different cache entry from the default, as any other reference would be.
    assert make_request("Yb", "b", configuration=spelling) != make_request("Yb", "b")


def test_an_unreachable_oxidation_state_is_refused():
    """The f-block formula only describes states with 0-14 f electrons; outside that it is not
    a description of anything and says so rather than returning a negative occupation."""
    with pytest.raises(ValueError, match="outside 0-14"):
        AtomicConfiguration.for_oxidation_state("Ce", 6)
    with pytest.raises(ValueError, match="electrons"):
        AtomicConfiguration.for_oxidation_state("Ne", 12)


def test_a_trivalent_configuration_is_refused_outside_the_f_block():
    """The restriction is the point: a d-block or main-group trivalent ion is a genuine
    chemical choice, and deriving one would be the ``"6p"`` AO-label class of silent error."""
    with pytest.raises(ValueError, match="only for the f blocks"):
        AtomicConfiguration.trivalent("Ti")
    with pytest.raises(ValueError, match="only for the f blocks"):
        AtomicConfiguration.trivalent("Bi")


def test_no_default_reference_has_two_open_shells_in_the_f_block():
    """Averaging over one open shell is a better-defined approximation than over two, and
    several *neutral* lanthanides have two — Ce is [Xe]4f1 5d1 6s2, open in both ``d`` and
    ``f``. The trivalent default removes that for every f-block element.

    ⚠ This is a benefit of the choice, **not** its justification, and not a bug fix: the
    occupations a two-open-shell configuration produces were measured and are clean (neutral
    Ce, density time-reversal odd at 1.7e-10 relative).
    """
    from kuiva.amf.configuration import F_BLOCKS, default_configuration
    from pyscf.data.elements import ELEMENTS

    for first, last, _, _ in F_BLOCKS:
        for z in range(first, last + 1):
            config = default_configuration(ELEMENTS[z])
            assert len(config.open_shells()) <= 1, ELEMENTS[z]
            assert config.n_electrons == z - 3, ELEMENTS[z]


# --- 3. Sphericity of the converged density ------------------------------------------------

@pytest.mark.parametrize("symbol,configuration", [
    ("C", "[He]2s2 2p2"),
    ("O", "[He]2s2 2p4"),
    ("Na", "[Ne]3s1"),
])
def test_the_averaged_density_is_spherical(symbol, configuration):
    """Under AOC the anisotropy check becomes the assertion that averaging worked.

    Measured: 1.5e-12 (C), 3.4e-13 (O), 1.6e-12 (Na) — the same population as a closed shell,
    and six orders of magnitude below the threshold. An aufbau occupation of the same atoms
    gives order unity (``test_amf_backend.py`` fires the guard by substituting one).
    """
    solution = atomic_solution(symbol, atom(symbol)._basis[symbol],
                               configuration=configuration)
    assert solution.converged
    mole = atom(symbol).decontract_basis(aggregate=True)[0]
    assert _density_anisotropy(mole, solution.density.ll) < 1e-3 * SPHERICAL_DENSITY_TOLERANCE


def test_an_open_shell_correction_is_structurally_sound():
    """Structural invariants on an **open-shell** correction.

    Real symmetric ``dh_sf``, real antisymmetric ``dw``, time-reversal even. These hold by
    construction of ``decompose_two_component`` — but the open-shell path reaches it through a
    fractionally occupied density, which is exactly the sort of change that can smuggle in a
    time-reversal-odd component without breaking hermiticity.
    """
    correction = amf_correction(atom("O"), method="x2camf", configuration="[He]2s2 2p4")
    validate_correction(correction.h_sf, correction.w, what="open-shell X2CAMF correction")
    assert correction.spin_orbit_scale > 0.0
    assert correction.tr_residual_rel < 1e-8
    assert correction.configurations == {"O": "s4 p4"}


# --- 4. The energy functional, generalized to open shells ----------------------------------

def average_of_configuration_ghf(mol, configuration, hcore):
    """A **two-component** SCF occupying ``configuration`` by average of configuration.

    The open-shell counterpart of ``test_amf_decouple.x2camf_energy``'s closed-shell GHF, and
    the thing the validation ladder asks to be built first. ⚠ Its whole job is to occupy *the same
    configuration the same way* the four-component reference did: the filling rule comes from
    :func:`kuiva.amf.configuration.average_occupations`, shared with
    :mod:`kuiva.amf.pyscf_dhf`, so the two cannot drift apart. Two implementations of one rule
    that agreed today would be a comparison waiting to become meaningless.

    Angular momentum is resolved by Mulliken population over the spin-blocked ``[alpha; beta]``
    AO basis — the same construction the four-component version uses on its large component.
    """
    import scipy.linalg
    from pyscf import scf

    s = mol.intor_symmetric("int1e_ovlp")
    s2c = scipy.linalg.block_diag(s, s)
    angular = np.concatenate([_ao_angular_momenta(mol)] * 2)

    state = {}

    def get_occ(mo_energy=None, mo_coeff=None):
        c = np.asarray(mo_coeff)
        population = np.real(np.conj(c) * (s2c @ c))
        channels = sorted(set(int(l) for l in angular))
        weights = np.stack([population[angular == l].sum(axis=0) for l in channels])
        assigned = np.asarray(channels)[np.argmax(weights, axis=0)]
        occ = average_occupations(configuration, np.asarray(mo_energy, dtype=float), assigned)
        # ⚠ Same capture as the four-component side, for the same reason: PySCF keeps
        # ``mo_coeff`` in a local through the SCF loop and only assigns the attribute after
        # convergence, so the shell-dependent Fock has nowhere else to read the orbitals from.
        state["mo_coeff"], state["mo_occ"] = c, occ
        shells = []
        for l, n_electrons in enumerate(configuration.occupations):
            degeneracy = 4 * l + 2
            q = n_electrons % degeneracy
            if not q:
                continue
            index = np.where((assigned == l) & (occ > 1e-12) & (occ < 1.0 - 1e-12))[0]
            shells.append(OpenShell(l, q, degeneracy, index))
        state["shells"] = shells
        return occ

    mf = scf.GHF(mol)
    mf.verbose = 0
    mf.conv_tol = 1e-11
    mf.max_cycle = 400
    mf.get_hcore = lambda *a, **k: hcore
    mf.get_ovlp = lambda *a, **k: s2c
    mf.get_occ = get_occ
    if not configuration.is_closed_shell:
        # ⚠ **The occupations alone are not average of configuration.** Without this the
        # two-electron energy is evaluated over the fractional density, whose open-open
        # coupling is ``(q/n)^2`` instead of ``q(q-1)/(n(n-1))`` — the recorded defect
        # records. It is installed here with the *same* function the four-component backend
        # uses, so the two sides of the energy-functional comparison provably minimize the
        # same functional as well as occupying the same configuration.
        install_configuration_average(mf, mol, state)
    mf.kernel()
    return mf


def _ao_angular_momenta(mol):
    """``l`` of every scalar AO, from the shell data rather than from label strings."""
    out = []
    for ib in range(mol.nbas):
        l = int(mol.bas_angular(ib))
        out.extend([l] * (int(mol.bas_nctr(ib)) * (2 * l + 1)))
    assert len(out) == mol.nao
    return np.asarray(out, dtype=int)


def x2camf_open_shell_energy(mol, configuration, dg_2c):
    """``E = Tr(D h_X2C) + 1/2 Tr(D dG) + 1/2 Tr(D G_nr[D]) + E_nuc`` at the AOC density.

    Note the factor of one half, which is the standard frozen-mean-field trap: ``dG`` is a
    two-electron mean field, so it enters the Fock operator **whole** and the energy **halved**.
    Getting only one of the two right differs by a factor of two in the total.
    """
    from pyscf.x2c import x2c

    from kuiva.spinor.expand import decompose_two_component, two_component_operator

    helper = x2c.SpinOrbitalX2CHelper(mol)
    helper.xuncontract = False
    h1 = two_component_operator(*decompose_two_component(np.asarray(helper.get_hcore())))
    mf = average_of_configuration_ghf(mol, configuration, h1 + dg_2c)
    assert mf.converged
    dm = mf.make_rdm1()
    return float(mf.e_tot - 0.5 * np.real(np.einsum("ij,ji->", dg_2c, dm)))


@pytest.mark.parametrize("symbol,configuration,tolerance", [
    ("C", "[He]2s2 2p2", 5e-6),
    ("O", "[He]2s2 2p4", 5e-6),
])
def test_open_shell_energy_functional_reproduces_four_component(symbol, configuration,
                                                                tolerance):
    """**The sharpest check available for an open shell, and it needs no external program.**

    X2CAMF is an approximation to four-component Dirac-Coulomb theory, so the statement that it
    *is* one is that its energy reproduces the four-component energy — same basis, same
    interaction, same speed of light, and now the same average-of-configuration reference
    state. For closed shells this separates the subtraction's density conventions by five to six
    orders of magnitude; it is what the validation ladder asks be extended here first.

    Measured: **3.1e-09 Eh (C 2p^2)** and **5.1e-08 Eh (O 2p^4)** against four-component
    Dirac-Coulomb, from -5.9e-05 and -3.2e-04 uncorrected — 19000x and 6200x, and *sharper*
    than the closed-shell Ne case (3.4e-07 Eh), so opening the shell degrades nothing. The
    tolerances below are two orders looser than that: they are a regression guard, not a fit.
    """
    clear_cache()
    mol = atom(symbol)
    solution = atomic_solution(symbol, mol._basis[symbol], configuration=configuration,
                               uncontract=False)
    assert solution.converged
    correction = amf_correction(mol, method="x2camf", configuration=configuration,
                                uncontract=False)
    energy = x2camf_open_shell_energy(mol, solution.configuration,
                                      correction.hamiltonian())
    assert abs(energy - solution.e_tot) < tolerance


@pytest.mark.parametrize("symbol,configuration", [("C", "[He]2s2 2p2"),
                                                  ("O", "[He]2s2 2p4")])
def test_the_uncorrected_open_shell_hamiltonian_is_measurably_worse(symbol, configuration):
    """The same comparison with no correction, so the number above means something.

    Asserting the *ratio* rather than either value is what makes this a statement about the
    correction rather than about the basis or the reference state.
    """
    clear_cache()
    mol = atom(symbol)
    solution = atomic_solution(symbol, mol._basis[symbol], configuration=configuration,
                               uncontract=False)
    correction = amf_correction(mol, method="x2camf", configuration=configuration,
                                uncontract=False)
    dg = correction.hamiltonian()
    with_amf = abs(x2camf_open_shell_energy(mol, solution.configuration, dg) - solution.e_tot)
    without = abs(x2camf_open_shell_energy(mol, solution.configuration,
                                           np.zeros_like(dg)) - solution.e_tot)
    assert without > 100.0 * with_amf


# --- 5. The reference configuration is a real choice ---------------------------------------

@pytest.mark.stage_under_test("amf_atomic")   # asserts a SOLVE COUNT: no cache may serve it
def test_the_reference_configuration_changes_the_correction():
    """Deliverable 4's question, in its cheapest form: does it matter at all?

    Oxygen's neutral 2p4 against the 2p3 of O(+) — the same element, the same basis, one
    electron of difference in the screening. If these came back equal, either the
    configuration is not reaching the mean field or the cache is aliasing them, and both
    failures would be silent. The magnitude of the difference is what
    ``tests/generate/amf_sensitivity.py`` measures for the ions that matter.
    """
    clear_cache()
    mol = atom("O")
    neutral = amf_correction(mol, method="x2camf", configuration="[He]2s2 2p4")
    ionic = amf_correction(mol, method="x2camf", configuration="[He]2s2 2p3")
    assert cache_statistics()["solves"] == 2            # two references, two solves
    assert neutral.spin_orbit_scale != ionic.spin_orbit_scale
    relative = abs(ionic.spin_orbit_scale - neutral.spin_orbit_scale) \
        / neutral.spin_orbit_scale
    assert 1e-3 < relative < 1.0     # a real effect, and not a different order of magnitude


def test_the_committed_sensitivity_study_says_the_choice_barely_matters():
    """The reference-configuration sensitivity study, asserted against the committed record.

    ⚠ **This is the honest answer to "is an atomic mean field valid for an ion in a ligand
    field", and it is the reason an in-house Breit-Pauli AMFI could be rejected.**
    Measured on Ti(3+) — the ion behind the reference systems ``ticl3`` and ``ti2cl6`` — in
    ``x2c-SVPall-2c``, decoupled in the primitive basis:

    ======================================= ================
    3d j-splitting, one-electron X2C          622.05 cm^-1
    ...corrected, **neutral Ti** reference    308.81 cm^-1
    ...corrected, **Ti(3+)** reference        309.44 cm^-1
    ======================================= ================

    Two readings. The correction is **large** for a 3d ion — it halves the splitting, far more
    than the 15-30% it removes for a p-block valence shell — so getting it at all matters more
    here than anywhere else in the target set. And the reference configuration changes the answer by
    **0.21%** on the observable and 0.04% on ``max |dw|``, i.e. essentially not at all: the
    picture change is a *core* effect, and stripping three valence electrons barely touches the
    core. That is what licenses the neutral-atom default.

    ⚠ It brackets the **configuration** only. No atomic calculation reaches the ligand field,
    and this number must not be quoted as though it did.
    """
    import json
    from pathlib import Path

    path = Path(__file__).resolve().parents[0] / "reference/amf_sensitivity.json"
    if not path.is_file():
        pytest.skip("run tests/generate/amf_sensitivity.py to create {}".format(path.name))
    records = json.loads(path.read_text())["records"]
    usable = {k: v for k, v in records.items() if v.get("status") == "ok"}
    if not usable:
        pytest.skip("no usable sensitivity records")
    for key, record in usable.items():
        s = record["sensitivity"]
        # The correction is a real effect...
        assert abs(record["neutral"]["splitting_cm"]
                   - record["uncorrected_splitting_cm"]) > 0.05 * abs(
                       record["uncorrected_splitting_cm"]), key
        # ...and the reference configuration is a small one. The band is 5%, an order of
        # magnitude above the observed 0.21%, because this is a claim about a *regime* — that
        # the atomic reference is not a leading error — not a fit to Ti(3+).
        assert s["splitting_relative"] < 0.05, key
        assert s["dw_relative"] < 0.05, key


def test_the_committed_fine_structure_records_improve_against_both_references():
    """The NIST fine-structure anchor, asserted against the committed record.

    Two comparisons per atom, and they are not interchangeable:

    * **against four-component theory in the same basis** — free, in-process, and the sharp
      statement that the picture change is right. Measured on Ne: 1170.95 -> **903.22 cm^-1**
      against a reference of 903.27, i.e. **-0.0065%**, from +29.6%.
    * **against experiment** — a 30% anchor, never an accuracy claim, and
      **only where one exists**. Ne: +50.0% uncorrected -> **+15.7%** with Dirac-Coulomb ->
      **+6.1%** with Gaunt.

    ⚠ That last pair is why the criterion has to be read with the **interaction held fixed**:
    Gaunt accounts for well over half of what is left after the correction, so attributing the
    whole residual to the reference configuration would be wrong: the interaction must be held
    fixed.

    ⚠ **Not every atom has an experimental anchor, and the absence is deliberate** (user
    decision). Bi's 6p^3 fine structure is a *term* splitting of a three-electron open shell,
    not a one-particle quantity — the four-component reference is itself +38% above it — so
    quoting it reads as a +38% method error where the four-component agreement is +0.018%.
    Records without one are still checked against four-component theory, which is the sharper
    comparison anyway.

    ⚠ And the four-component column is only meaningful because both sides are in the
    **primitive** basis. Run the two-component side contracted against a primitive reference
    and Ne reads +0.272% instead of -0.007% — a basis change read as method error, which is the
    basis-mismatch trap.
    """
    import json
    from pathlib import Path

    path = Path(__file__).resolve().parents[0] / "reference/amf_fine_structure.json"
    if not path.is_file():
        pytest.skip("run tests/generate/amf_fine_structure.py to create {}".format(path.name))
    records = {k: v for k, v in json.loads(path.read_text())["records"].items()
               if v.get("status") == "ok"}
    if not records:
        pytest.skip("no usable fine-structure records")
    for key, record in records.items():
        assert record["four_component_converged"], key
        # The correction must beat the one-electron operator against four-component theory by
        # a wide margin. 100x is ~10x below the observed 10^4 for Ne and is a regression guard.
        assert abs(record["corrected_vs_4c"]) * 100.0 < abs(record["uncorrected_vs_4c"]), key
        assert abs(record["corrected_vs_4c"]) < 5e-3, key
        assert record["construction"].startswith("self-consistent two-component"), key
        # ...and where a one-particle experimental anchor exists, it must move toward it.
        if record.get("experiment_cm"):
            assert abs(record["corrected_vs_experiment"]) \
                < abs(record["uncorrected_vs_experiment"]), key
        else:
            # The absence is a recorded decision, so it carries its reason with it.
            assert record["experiment_note"], key


@pytest.mark.slow
def test_titanium_three_plus_converges_from_a_cold_start():
    """Ti(3+) d1 — the ion behind the reference systems ``ticl3`` and ``ti2cl6``, and the cheapest
    member of the open-shell set.

    Nothing is seeded from a previous solution: the cold start is the point.
    The single d electron is spread 1/10 over the ten d spinors, and the converged density is
    spherical to 5e-13.
    """
    clear_cache()
    mol = atom("Ti", charge=3)
    solution = atomic_solution("Ti", mol._basis["Ti"], configuration="[Ar]3d1")
    assert solution.converged and solution.charge == 3
    occ = np.asarray(solution.mo_occ)
    fractional = np.sort(occ[(occ > 1e-12) & (occ < 1.0 - 1e-12)])
    assert fractional.size == 10 and np.allclose(fractional, 0.1)
    assert _density_anisotropy(
        atom("Ti", charge=3).decontract_basis(aggregate=True)[0],
        solution.density.ll) < 1e-3 * SPHERICAL_DENSITY_TOLERANCE
