"""Configuration recovery: measured bitstrings to a determinant space.

**Orchestration, not a registered kernel.**

What this step is for
---------------------
A sampled bitstring is a computational-basis outcome, not a determinant. The circuits of
:mod:`kuiva.qc.ansatz` do not conserve particle number — hardware-efficient ones by
definition, and even a number-conserving circuit would not on a noisy device — so a raw shot
record contains configurations with the wrong electron count. Recovery is the classical step
that turns the record into a set of masks with **exactly** ``n_elec`` electrons, which is what
``ci/strings.Determinants`` accepts and what the subspace Hamiltonian is built over.

Two policies, and the difference between them is a decision, not a tuning knob:

``"project"``
    Discard every bitstring with the wrong particle number. Exact, deterministic, assumption
    free — and on a hardware-efficient ansatz it throws away most of the shots. The **yield**
    is therefore reported, always: a recovery that silently kept 3% of the budget while the
    caller believed it had spent 100000 shots is a shot count that means nothing.
``"repair"``
    Move the wrong-``N`` bitstrings onto the right particle number by flipping the modes least
    (or most) likely to be occupied, judged by the average occupancy of the *correctly
    numbered* part of the same record. This is the configuration-recovery idea of the SQD
    literature and it is what makes the shot budget usable.

⚠ **Kuiva's repair is deterministic where the published one samples.** The literature draws
the flipped modes from a Bernoulli distribution built on the average occupancy; here the modes
are ranked by that same occupancy and the extreme ones are flipped, ties broken by index. The
reason is the provenance-travels-with-the-result rule: a simulator result must be replayable from its recorded
seed, and a deterministic recovery makes the *classical* half of that unconditional rather
than one more thing depending on an RNG stream. It is a documented deviation, not an
oversight, and it costs diversity — a probabilistic repair explores more configurations per
shot, which is why it is the published choice.

⚠ **Recovery cannot invent information.** Repair moves a bitstring to the nearest plausible
configuration; it does not make a bad sampling distribution good. If the yield before repair
is a few percent, the recovered space is mostly an artefact of the occupancy heuristic and the
subspace energy will say so by being poor. Read the pre-repair yield, not the post-repair
count.

``"kramers"``
    ``"repair"``, and then **close the recovered space under time reversal**: for every
    retained configuration, its Kramers partner is retained too, and the two pool their shot
    counts. Kuiva-specific, with no counterpart in the (spin-separable, not Kramers-structured)
    literature this module is otherwise drawn from.

⚠ **What closure buys is a theorem, not an average improvement.** A time-reversal-symmetric
Hamiltonian has exactly degenerate Kramers pairs; an *arbitrary* sampled subspace is not
``T``-invariant, so the projected Hamiltonian in it is not either, and the pair splits by an
arbitrary amount — an amount that lands squarely in the 1e-8..1e-6 Eh band reserved for a
*genuine* numerical Kramers splitting, and is therefore indistinguishable from it by
inspection. A ``T``-closed subspace restores the degeneracy **exactly**, at machine precision,
because the projector then commutes with ``T``. The measured splitting with and without closure
(1.2 Eh of invented splitting removed on the Fe(2+) test case) is the strongest argument for this policy: not
that the energy is better, but that a symmetry the answer is supposed to have stops being an
accident of which bitstrings were drawn.

⚠ **A cap truncates whole Kramers orbits, never half of one** — the whole-degenerate-group rule
("truncate whole degenerate groups, never individual vectors") at a third place in the code.
Orbits are ranked by their *pooled* count, which is also the statistically right thing: two
partners are sampled from distributions related by an exact symmetry, so their counts are two
measurements of one number. A cap that cannot be met exactly is met **from below**, since
overshooting it would break the memory reservation the caller made.

What is deliberately not here
-----------------------------
⚠ **Kramers-based qubit reduction, and the reason is a negative result worth recording rather
than an omission.** The design pairs "Kramers-aware recovery" with "and/or qubit
reduction", and the natural hope is that time reversal tapers a qubit the way particle number
and spin parity do. It does not, and cannot: qubit tapering works on a ``Z2`` symmetry
generated by a **Pauli** operator commuting with the Hamiltonian, and time reversal is
*antiunitary* — it is not an element of the Pauli group and has no representation as one. The
symmetry is real and exploitable (this policy, and the planned Kramers-restricted CI mode), but not
by tapering. Recorded so nobody spends the effort twice.

References
----------------------------
* Self-consistent configuration recovery, the procedure this module implements a
  deterministic variant of: "Chemistry beyond the scale of exact diagonalization on a
  quantum-centric supercomputer", *Sci. Adv.* (2025), doi:10.1126/sciadv.adu9991; the
  reference implementation in ``qiskit-addon-sqd``, github.com/Qiskit/qiskit-addon-sqd.
* Kramers degeneracy: H. A. Kramers, *Proc. Amsterdam Acad.* **33**, 959 (1930); the
  time-reversal conventions are ``kuiva/spinor/expand.py``'s.
* Qubit tapering from ``Z2`` Pauli symmetries — the technique that does **not** apply to time
  reversal: S. Bravyi, J. M. Gambetta, A. Mezzacapo, K. Temme, "Tapering off qubits to simulate
  fermionic Hamiltonians", arXiv:1701.08213 (2017).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple

import numpy as np

from ..ci.strings import Determinants, kramers_partner, popcount
from ..util.logging import get_logger

log = get_logger(__name__)

_U64 = np.uint64

#: The policies :func:`recover_configurations` accepts. ⚠ ``"kramers"`` implies ``"repair"``;
#: there is no ``"project"`` + closure combination, because projection already discards most of
#: a hardware-efficient budget and closing what little survives measures the closure rather
#: than the sampler.
POLICIES = ("project", "repair", "kramers")


@dataclass(frozen=True)
class RecoveryResult:
    """A determinant space and an honest account of what it cost to get it.

    Attributes
    ----------
    determinants : Determinants
        Unique masks with exactly ``n_elec`` electrons, ascending. ⚠ The CI space, with no
        weighting: the sampled *counts* are kept separately because they are evidence about
        the distribution, not amplitudes.
    counts : ndarray (ndet,) int64
        Shots supporting each retained configuration, in the same order.
    shots : int — the whole budget the record came from.
    kept : int — shots whose bitstring already had the right particle number.
    repaired : int — shots moved onto the right particle number.
    closure_added : int
        Configurations the ``"kramers"`` policy added because their time-reversed partner had
        been sampled but they had not. ⚠ The honest reading of a *large* value: the sampler is
        not respecting a symmetry the Hamiltonian has, and closure is doing the work the
        circuit should have done. It is still the right thing to do — see the module docstring
        — but it is a statement about the ansatz.
    kramers_closed : bool — whether the space is closed under time reversal.
    """

    determinants: Determinants
    counts: np.ndarray
    shots: int
    kept: int
    repaired: int
    closure_added: int = 0
    kramers_closed: bool = False

    @property
    def ndet(self) -> int:
        return self.determinants.ndet

    @property
    def yield_fraction(self) -> float:
        """⚠ Shots that were **already** valid, over the whole budget.

        The pre-repair number, deliberately: it is the one that says whether the sampling
        distribution is any good. Post-repair "yield" is close to 1 by construction and
        measures the heuristic rather than the circuit.
        """
        return self.kept / max(1, self.shots)

    @property
    def used_fraction(self) -> float:
        """Shots that ended up in the space, valid or repaired."""
        return (self.kept + self.repaired) / max(1, self.shots)

    def __repr__(self) -> str:
        return ("RecoveryResult(ndet={}, shots={}, yield={:.1%}, used={:.1%}{})"
                .format(self.ndet, self.shots, self.yield_fraction, self.used_fraction,
                        ", T-closed" if self.kramers_closed else ""))


def _occupancy(masks: np.ndarray, counts: np.ndarray, n_qubit: int) -> np.ndarray:
    """Shot-weighted average occupancy of each mode, in ``[0, 1]``."""
    bits = np.array([(masks >> _U64(k)) & _U64(1) for k in range(n_qubit)],
                    dtype=np.float64)                                     # (n_qubit, n)
    total = float(counts.sum())
    if total <= 0.0:
        return np.full(n_qubit, 0.5)
    return bits @ (counts.astype(np.float64) / total)


def _repair(masks: np.ndarray, n_elec: int, n_qubit: int,
            occupancy: np.ndarray) -> np.ndarray:
    """Move each mask onto ``n_elec`` electrons by flipping the least-likely modes.

    Deterministic (see the module docstring). A mask with too many electrons loses the
    occupied modes of *lowest* average occupancy; one with too few gains the empty modes of
    *highest*. Ties break on mode index, which is arbitrary but fixed — and being fixed is the
    property that matters, since it is what makes a rerun reproduce the same space.

    ⚠ A Python loop over the *distinct* wrong-``N`` outcomes, ``O(n_wrong * n_qubit)``. That
    is nothing at the sizes reached today (a few hundred distinct outcomes over ten modes) and
    it is the first thing to vectorize if a sampled subspace ever reaches the ``10^5``-plus
    regime the SQD literature quotes. Recorded rather than pre-optimized: the rule is that an
    unprofiled optimization is a guess.
    """
    order_low = np.argsort(occupancy, kind="stable")        # least occupied first
    order_high = order_low[::-1]
    out = np.empty(masks.size, dtype=_U64)
    for i, raw in enumerate(masks.tolist()):
        mask = int(raw)
        excess = int(bin(mask).count("1")) - int(n_elec)
        if excess > 0:
            for mode in order_low:
                if excess == 0:
                    break
                if (mask >> int(mode)) & 1:
                    mask &= ~(1 << int(mode))
                    excess -= 1
        elif excess < 0:
            for mode in order_high:
                if excess == 0:
                    break
                if not (mask >> int(mode)) & 1:
                    mask |= 1 << int(mode)
                    excess += 1
        out[i] = _U64(mask)
    return out


def recover_configurations(masks: np.ndarray, counts: np.ndarray, n_elec: int,
                           n_qubit: int, *, policy: str = "repair",
                           max_determinants: Optional[int] = None,
                           prior: Optional[Tuple[np.ndarray, np.ndarray]] = None
                           ) -> RecoveryResult:
    """Turn a shot record into a determinant space (module docstring for the policies).

    Parameters
    ----------
    masks, counts : the backend's :class:`~kuiva.qc.backend.SampleResult` arrays.
    n_elec, n_qubit : the active space.
    policy : ``"project"`` or ``"repair"``.
    max_determinants : int, optional
        Cap on the space. ⚠ A cap **truncates by accumulated shot count**, so the
        configurations that survive are the ones the sampling has found most often — not the
        ones with the largest CI coefficient, which nobody knows yet. That is the honest
        ordering available at this point and it is what makes the subspace energy a
        variational bound and nothing stronger.
    prior : ``(masks, counts)``, optional
        Evidence carried over from earlier draws — how the incumbent subspace crosses an SQD
        iteration. Prior counts are **added** to the new ones before any cap is applied.

        ⚠ **Added, not treated as a floor, and that distinction was a live defect.** Giving
        the incumbent configurations a count above every sampled one makes them unevictable,
        so under a binding cap the space freezes at the first draw and every later proposal
        reproduces it exactly — the sampler runs, costs shots, and can no longer change
        anything. Accumulating instead means a configuration seen consistently across rounds
        survives and one seen once does not, which is both the statistically sound rule and
        the one that lets the space actually evolve.

        ⚠ Prior particle numbers are checked, not assumed.

    Returns
    -------
    RecoveryResult
    """
    if policy not in POLICIES:
        raise ValueError("unknown recovery policy {!r}; implemented: {}. Kramers-parity-aware "
                         "recovery is planned and is not registered."
                         .format(policy, ", ".join(POLICIES)))
    masks = np.ascontiguousarray(masks, dtype=_U64)
    counts = np.ascontiguousarray(counts, dtype=np.int64)
    if masks.shape != counts.shape or masks.ndim != 1:
        raise ValueError("masks {} and counts {} must be matching 1-D arrays".format(
            masks.shape, counts.shape))
    n_elec, n_qubit = int(n_elec), int(n_qubit)
    shots = int(counts.sum())

    valid = popcount(masks) == n_elec
    kept = int(counts[valid].sum())
    repaired = 0
    if policy in ("repair", "kramers") and not np.all(valid):
        occupancy = _occupancy(masks[valid], counts[valid], n_qubit)
        if not np.any(valid):
            # Nothing to build an occupancy from. ⚠ Falling back to the whole record is the
            # honest choice: an occupancy estimated from wrong-N bitstrings is a weak
            # heuristic, but a uniform one is no heuristic at all, and the yield below is
            # what tells the caller the estimate was made this way.
            occupancy = _occupancy(masks, counts, n_qubit)
            log.warning("no sampled bitstring had the right particle number (%d of %d "
                        "electrons); the repair occupancy is estimated from the wrong-N "
                        "record itself and the recovered space is a heuristic artefact",
                        n_elec, n_qubit)
        fixed = _repair(masks[~valid], n_elec, n_qubit, occupancy)
        repaired = int(counts[~valid].sum())
        masks = np.concatenate([masks[valid], fixed])
        counts = np.concatenate([counts[valid], counts[~valid]])
    else:
        masks, counts = masks[valid], counts[valid]

    unique, inverse = np.unique(masks, return_inverse=True)
    totals = np.bincount(inverse, weights=counts.astype(np.float64),
                         minlength=unique.size).astype(np.int64)

    if prior is not None and np.asarray(prior[0]).size:
        prior_masks = np.ascontiguousarray(prior[0], dtype=_U64)
        prior_counts = np.ascontiguousarray(prior[1], dtype=np.int64)
        if prior_masks.shape != prior_counts.shape:
            raise ValueError("prior masks {} and counts {} must match".format(
                prior_masks.shape, prior_counts.shape))
        bad = popcount(prior_masks) != n_elec
        if np.any(bad):
            raise ValueError("prior= carries {} mask(s) with the wrong particle number; a "
                             "determinant space may not mix electron counts".format(
                                 int(bad.sum())))
        unique = np.concatenate([unique, prior_masks])
        totals = np.concatenate([totals, prior_counts])
        unique, inverse = np.unique(unique, return_inverse=True)
        totals = np.bincount(inverse, weights=totals.astype(np.float64),
                             minlength=unique.size).astype(np.int64)

    added = 0
    if policy == "kramers":
        before = unique.size
        unique, totals = _close_under_time_reversal(unique, totals, n_qubit)
        added = int(unique.size - before)

    if max_determinants is not None and unique.size > int(max_determinants):
        if policy == "kramers":
            unique, totals = _cap_orbits(unique, totals, int(max_determinants))
        else:
            # Stable sort on the negated counts: ties keep ascending mask order, so the
            # truncation is reproducible rather than dependent on the sort's internals.
            order = np.sort(np.argsort(-totals, kind="stable")[:int(max_determinants)])
            unique, totals = unique[order], totals[order]

    dets = Determinants(masks=unique, n_spinor=n_qubit, n_elec=n_elec)
    result = RecoveryResult(determinants=dets, counts=totals, shots=shots, kept=kept,
                            repaired=repaired, closure_added=added,
                            kramers_closed=(policy == "kramers"))
    log.debug("configuration recovery (%s): %d shots -> %d configurations, yield %.1f%%, "
              "used %.1f%%%s", policy, shots, result.ndet, 100.0 * result.yield_fraction,
              100.0 * result.used_fraction,
              ", {} added by time-reversal closure".format(added) if added else "")
    return result


def _close_under_time_reversal(masks: np.ndarray, counts: np.ndarray, n_qubit: int
                               ) -> Tuple[np.ndarray, np.ndarray]:
    """Add every missing Kramers partner and pool each orbit's shot counts.

    Both members of an orbit come out carrying the **same** count, the orbit's total: they are
    two measurements of one number, related by an exact symmetry, so any later ranking — a cap,
    a report — should not be able to prefer one over the other by sampling noise.
    """
    if n_qubit % 2:
        raise ValueError("time-reversal closure needs Kramers-paired spinors, so an even mode "
                         "count; got {}. With an unrestricted reference the spinors are "
                         "not partnered at all and this policy does not apply.".format(n_qubit))
    partners = kramers_partner(masks)
    self_paired = partners == masks
    pooled_masks = np.concatenate([masks, partners[~self_paired]])
    pooled_counts = np.concatenate([counts, counts[~self_paired]])
    out, inverse = np.unique(pooled_masks, return_inverse=True)
    totals = np.bincount(inverse, weights=pooled_counts.astype(np.float64),
                         minlength=out.size).astype(np.int64)
    return out, totals


def _cap_orbits(masks: np.ndarray, counts: np.ndarray, cap: int
                ) -> Tuple[np.ndarray, np.ndarray]:
    """Truncate to ``<= cap`` determinants keeping **whole** Kramers orbits.

    ⚠ Half an orbit is worse than one orbit fewer: it breaks the closure the policy exists to
    establish, and the resulting subspace splits a degeneracy that the Hamiltonian does not.
    So the cap is met **from below** — the whole-degenerate-group truncation rule, at a third place
    in the code.
    """
    partners = kramers_partner(masks)
    representative = np.minimum(masks, partners)
    reps, orbit = np.unique(representative, return_inverse=True)
    score = np.zeros(reps.size, dtype=np.int64)
    np.maximum.at(score, orbit, counts)
    size = np.bincount(orbit, minlength=reps.size)
    keep = np.zeros(reps.size, dtype=bool)
    used = 0
    for r in np.argsort(-score, kind="stable").tolist():
        if used + int(size[r]) > cap:
            continue
        keep[r] = True
        used += int(size[r])
    take = np.flatnonzero(keep[orbit])
    return masks[take], counts[take]


def subspace_fraction(ndet: int, n_qubit: int, n_elec: int) -> float:
    """Recovered space as a fraction of the complete CAS space.

    The figure that says whether a sampled-subspace result is a *method* result or an exact
    CI wearing a sampling costume: at 1.0 the subspace **is** the full CI and reproducing
    ``FullCISolver`` proves the pipeline, not the algorithm.
    """
    from ..ci.strings import cas_dimension

    total = cas_dimension(int(n_qubit), int(n_elec))
    return float(ndet) / float(total) if total else 0.0


__all__ = ["POLICIES", "RecoveryResult", "recover_configurations", "subspace_fraction"]
